name: yash
on:
  push:
    branches:
      - main
env: 
  tag_value: ${{github.sha}}
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: aws credential's
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          docker  build -f Dockerfile -t 989007362438.dkr.ecr.ap-south-1.amazonaws.com/app:${{env.tag_value}} .
          docker push 989007362438.dkr.ecr.ap-south-1.amazonaws.com/app:${{env.tag_value}}
  deploy:
  runs-on: ubuntu-latest
  needs: docker-build

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Pull existing ECS Task Definition
      id: task-def
      run: |
        aws ecs describe-task-definition --task-definition demo --query taskDefinition > task-def.json

    - name: Update Task Definition Image
      id: update-image
      run: |
        NEW_IMAGE="989007362438.dkr.ecr.ap-south-1.amazonaws.com/app:${{ env.tag_value }}"
        echo "Updating image to $NEW_IMAGE"
        sed -i "s|\"image\": \".*\"|\"image\": \"$NEW_IMAGE\"|" task-def.json

    - name: Register Updated Task Definition
      id: register-task
      run: |
        aws ecs register-task-definition \
          --cli-input-json file://task-def.json \
          --query "taskDefinition.taskDefinitionArn" > task-arn.txt
        echo "task_definition_arn=$(cat task-arn.txt)" >> $GITHUB_ENV

    - name: Deploy New Task Definition to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ env.task_definition_arn }}
        service: ecs-service
        cluster: ecs-cluster
        wait-for-service-stability: true
